[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqlnd", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.bcmath", "php82Extensions.ctype", "php82Extensions.fileinfo", "composer", "nodejs_20"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"

DB_CONNECTION=mysql
DB_HOST = mysql.railway.internal;    
DB_PORT=3306
DB_DATABASE = railway;  
DB_USERNAME=root
DB_PASSWORD = osvoRfHsxrblmsXnQjEBHLiREDWmdoFn;